// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdi

import (
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked Interface
//		mockedInterface := &InterfaceMock{
//			AdditionalDevicesFunc: func() []string {
//				panic("mock out the AdditionalDevices method")
//			},
//			CreateSpecFileFunc: func() error {
//				panic("mock out the CreateSpecFile method")
//			},
//			QualifiedNameFunc: func(s1 string, s2 string) string {
//				panic("mock out the QualifiedName method")
//			},
//		}
//
//		// use mockedInterface in code that requires Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// AdditionalDevicesFunc mocks the AdditionalDevices method.
	AdditionalDevicesFunc func() []string

	// CreateSpecFileFunc mocks the CreateSpecFile method.
	CreateSpecFileFunc func() error

	// QualifiedNameFunc mocks the QualifiedName method.
	QualifiedNameFunc func(s1 string, s2 string) string

	// calls tracks calls to the methods.
	calls struct {
		// AdditionalDevices holds details about calls to the AdditionalDevices method.
		AdditionalDevices []struct {
		}
		// CreateSpecFile holds details about calls to the CreateSpecFile method.
		CreateSpecFile []struct {
		}
		// QualifiedName holds details about calls to the QualifiedName method.
		QualifiedName []struct {
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
	}
	lockAdditionalDevices sync.RWMutex
	lockCreateSpecFile    sync.RWMutex
	lockQualifiedName     sync.RWMutex
}

// AdditionalDevices calls AdditionalDevicesFunc.
func (mock *InterfaceMock) AdditionalDevices() []string { _ = "STUB: not implemented"; return nil }

// AdditionalDevicesCalls gets all the calls that were made to AdditionalDevices.
// Check the length with:
//
//	len(mockedInterface.AdditionalDevicesCalls())
func (mock *InterfaceMock) AdditionalDevicesCalls() []struct {
} {
	_ = "STUB: not implemented"
	return nil
}

// CreateSpecFile calls CreateSpecFileFunc.
func (mock *InterfaceMock) CreateSpecFile() error { _ = "STUB: not implemented"; return nil }

// CreateSpecFileCalls gets all the calls that were made to CreateSpecFile.
// Check the length with:
//
//	len(mockedInterface.CreateSpecFileCalls())
func (mock *InterfaceMock) CreateSpecFileCalls() []struct {
} {
	_ = "STUB: not implemented"
	return nil
}

// QualifiedName calls QualifiedNameFunc.
func (mock *InterfaceMock) QualifiedName(s1 string, s2 string) string {
	_ = "STUB: not implemented"
	return ""
}

// QualifiedNameCalls gets all the calls that were made to QualifiedName.
// Check the length with:
//
//	len(mockedInterface.QualifiedNameCalls())
func (mock *InterfaceMock) QualifiedNameCalls() []struct {
	S1 string
	S2 string
} {
	_ = "STUB: not implemented"
	return nil
}
